/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.defence.maincontroller;

import com.defence.utilities.DefenceObservableInterface;
import com.defence.utilities.Strength;

/**
 *
 * @author shami
 */
public class MainController extends javax.swing.JFrame implements MainControllerInterface {

    private final DefenceObservableInterface defenceObservableInterface;

    /**
     * Creates new form MainController
     *
     * @param defenceObservableInterface
     */
    public MainController(DefenceObservableInterface defenceObservableInterface) {
        initComponents();
        setVisible(true);
        this.defenceObservableInterface = defenceObservableInterface;

    }

    @Override
    public void getMsg(String msg) {
        recievedMessages.append("\n" + msg);
    }

    public void addUnitsToComboList(javax.swing.JComboBox<String> comboBox) {
        int index = comboBox.getSelectedIndex();
        comboBox.removeAllItems();
        String[] allUnits = defenceObservableInterface.getAllUnits();
        for (String unit : allUnits) {
            comboBox.addItem(unit);
        }
        comboBox.setSelectedIndex(index);
    }

    @Override
    public void reportStatusChange() {
        updateUnitStatus();
    }

    ;
     private void updateUnitStatus() {
        int index = unitStatusComboBox.getSelectedIndex();
        if (index != -1) {
            currentTrackUnit.setText((String)unitStatusComboBox.getSelectedItem());
            String status = defenceObservableInterface.getStatusOfUnitInIndex(index);
            unitStatusTextArea.setText(status);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sendMessageGroup = new javax.swing.ButtonGroup();
        positionPanel = new javax.swing.JPanel();
        isAreaCleared = new javax.swing.JCheckBox();
        recMsgPanel = new javax.swing.JPanel();
        recMsgTitle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        recievedMessages = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        unitStatusTextArea = new javax.swing.JTextArea();
        currentTrackUnitLable = new javax.swing.JLabel();
        currentTrackUnit = new javax.swing.JLabel();
        unitStatusComboBox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        strengthSlider = new javax.swing.JSlider();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        sendButton = new javax.swing.JButton();
        sendAllSelection = new javax.swing.JRadioButton();
        sendUnitSelection = new javax.swing.JRadioButton();
        sendUnitSelectionBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        msgToSend = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Controller");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        positionPanel.setBackground(new java.awt.Color(204, 204, 204));
        positionPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        isAreaCleared.setBackground(new java.awt.Color(204, 204, 204));
        isAreaCleared.setFont(new java.awt.Font("Dubai", 1, 10)); // NOI18N
        isAreaCleared.setText("Area Cleared");
        isAreaCleared.setOpaque(true);
        isAreaCleared.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isAreaClearedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout positionPanelLayout = new javax.swing.GroupLayout(positionPanel);
        positionPanel.setLayout(positionPanelLayout);
        positionPanelLayout.setHorizontalGroup(
            positionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, positionPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(isAreaCleared)
                .addGap(16, 16, 16))
        );
        positionPanelLayout.setVerticalGroup(
            positionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, positionPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(isAreaCleared, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        recMsgPanel.setBackground(new java.awt.Color(204, 204, 204));
        recMsgPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        recMsgTitle.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        recMsgTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        recMsgTitle.setText("Unit Messages");

        recievedMessages.setEditable(false);
        recievedMessages.setBackground(new java.awt.Color(204, 255, 255));
        recievedMessages.setColumns(20);
        recievedMessages.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        recievedMessages.setLineWrap(true);
        recievedMessages.setRows(5);
        jScrollPane2.setViewportView(recievedMessages);

        javax.swing.GroupLayout recMsgPanelLayout = new javax.swing.GroupLayout(recMsgPanel);
        recMsgPanel.setLayout(recMsgPanelLayout);
        recMsgPanelLayout.setHorizontalGroup(
            recMsgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recMsgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(recMsgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(recMsgTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(recMsgPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        recMsgPanelLayout.setVerticalGroup(
            recMsgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recMsgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(recMsgTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });

        unitStatusTextArea.setEditable(false);
        unitStatusTextArea.setBackground(new java.awt.Color(204, 255, 255));
        unitStatusTextArea.setColumns(20);
        unitStatusTextArea.setFont(new java.awt.Font("Dubai", 1, 10)); // NOI18N
        unitStatusTextArea.setRows(5);
        jScrollPane3.setViewportView(unitStatusTextArea);

        currentTrackUnitLable.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        currentTrackUnitLable.setText("Currently Tracking :  ");

        currentTrackUnit.setBackground(new java.awt.Color(0, 102, 51));
        currentTrackUnit.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        currentTrackUnit.setForeground(new java.awt.Color(255, 255, 255));
        currentTrackUnit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        currentTrackUnit.setOpaque(true);

        unitStatusComboBox.setFont(new java.awt.Font("Dubai", 1, 10)); // NOI18N
        unitStatusComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                unitStatusComboBoxItemStateChanged(evt);
            }
        });
        unitStatusComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unitStatusComboBoxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                unitStatusComboBoxMouseEntered(evt);
            }
        });
        unitStatusComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitStatusComboBoxActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 204, 153));
        jButton1.setFont(new java.awt.Font("Dubai", 1, 10)); // NOI18N
        jButton1.setText("Track Status");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("UnitStatus Tracking");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(currentTrackUnitLable)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(currentTrackUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(unitStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unitStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(currentTrackUnitLable, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currentTrackUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        jLabel2.setBackground(new java.awt.Color(153, 51, 0));
        jLabel2.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Main Controller");
        jLabel2.setOpaque(true);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Strength");

        strengthSlider.setBackground(new java.awt.Color(204, 204, 204));
        strengthSlider.setFont(new java.awt.Font("Dubai", 1, 10)); // NOI18N
        strengthSlider.setMajorTickSpacing(10);
        strengthSlider.setMinorTickSpacing(5);
        strengthSlider.setPaintLabels(true);
        strengthSlider.setPaintTicks(true);
        strengthSlider.setValue(0);
        strengthSlider.setOpaque(true);
        strengthSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                strengthSliderStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(strengthSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(strengthSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel4.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        jLabel4.setText("Send to Units");

        sendButton.setBackground(new java.awt.Color(255, 204, 51));
        sendButton.setFont(new java.awt.Font("Dubai", 1, 12)); // NOI18N
        sendButton.setText("send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        sendAllSelection.setBackground(new java.awt.Color(204, 204, 204));
        sendMessageGroup.add(sendAllSelection);
        sendAllSelection.setFont(new java.awt.Font("Dubai", 1, 10)); // NOI18N
        sendAllSelection.setText("to All Units");
        sendAllSelection.setOpaque(true);
        sendAllSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendAllSelectionActionPerformed(evt);
            }
        });

        sendUnitSelection.setBackground(new java.awt.Color(204, 204, 204));
        sendMessageGroup.add(sendUnitSelection);
        sendUnitSelection.setFont(new java.awt.Font("Dubai", 1, 10)); // NOI18N
        sendUnitSelection.setText("to a Selectecd Unit");
        sendUnitSelection.setOpaque(true);
        sendUnitSelection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendUnitSelectionMouseClicked(evt);
            }
        });
        sendUnitSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendUnitSelectionActionPerformed(evt);
            }
        });

        sendUnitSelectionBox.setFont(new java.awt.Font("Dubai", 1, 10)); // NOI18N
        sendUnitSelectionBox.setToolTipText("Select a Unit");
        sendUnitSelectionBox.setEnabled(false);
        sendUnitSelectionBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendUnitSelectionBoxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sendUnitSelectionBoxMouseEntered(evt);
            }
        });
        sendUnitSelectionBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendUnitSelectionBoxActionPerformed(evt);
            }
        });

        msgToSend.setColumns(20);
        msgToSend.setFont(new java.awt.Font("Dubai", 1, 10)); // NOI18N
        msgToSend.setLineWrap(true);
        msgToSend.setRows(5);
        jScrollPane1.setViewportView(msgToSend);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(sendUnitSelection)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sendUnitSelectionBox, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(sendButton))
                            .addComponent(sendAllSelection)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sendButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sendAllSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sendUnitSelectionBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendUnitSelection, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(positionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(recMsgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(recMsgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(positionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(3, 3, 3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        // TODO add your handling code here:
        if (sendAllSelection.isSelected()) {
            if (!msgToSend.getText().equals("")) {
                defenceObservableInterface.sendMsgtoAllUnits("Commandar(Public) : " + msgToSend.getText() + "\n");
                msgToSend.setText("");
            }
        }
        if (sendUnitSelection.isSelected()) {
            if (!msgToSend.getText().equals("")) {
                int indexOfSelection = sendUnitSelectionBox.getSelectedIndex();
                defenceObservableInterface.sendMsgtoUnitInIndex(indexOfSelection, ("Commandar(Private) : " + msgToSend.getText() + "\n"));
                msgToSend.setText("");
            }
        }

    }//GEN-LAST:event_sendButtonActionPerformed

    private void sendAllSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendAllSelectionActionPerformed
        // TODO add your handling code here:
        sendUnitSelectionBox.setEnabled(false);
    }//GEN-LAST:event_sendAllSelectionActionPerformed

    private void sendUnitSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendUnitSelectionActionPerformed
        // TODO add your handling code here:

        sendUnitSelectionBox.setEnabled(true);
    }//GEN-LAST:event_sendUnitSelectionActionPerformed

    private void sendUnitSelectionBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendUnitSelectionBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendUnitSelectionBoxActionPerformed

    private void sendUnitSelectionBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendUnitSelectionBoxMouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_sendUnitSelectionBoxMouseEntered

    private void sendUnitSelectionBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendUnitSelectionBoxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sendUnitSelectionBoxMouseClicked

    private void isAreaClearedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isAreaClearedActionPerformed
        // TODO add your handling code here:
        defenceObservableInterface.sendAreaStatus(isAreaCleared.isSelected());
    }//GEN-LAST:event_isAreaClearedActionPerformed

    private void unitStatusComboBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unitStatusComboBoxMouseEntered
        // TODO add your handling code here:
      
    }//GEN-LAST:event_unitStatusComboBoxMouseEntered

    private void unitStatusComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitStatusComboBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_unitStatusComboBoxActionPerformed

    private void unitStatusComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_unitStatusComboBoxItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_unitStatusComboBoxItemStateChanged

    private void unitStatusComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unitStatusComboBoxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_unitStatusComboBoxMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        updateUnitStatus(); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        // TODO add your handling code here:
          addUnitsToComboList(unitStatusComboBox);
    }//GEN-LAST:event_jPanel1MouseEntered

    private void sendUnitSelectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendUnitSelectionMouseClicked
        // TODO add your handling code here:
         addUnitsToComboList(sendUnitSelectionBox);
    }//GEN-LAST:event_sendUnitSelectionMouseClicked

    private void strengthSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_strengthSliderStateChanged
        // TODO add your handling code here:
        int value = strengthSlider.getValue();
        Strength strength;
        if(value==0){
            strength = Strength.CLOSED;
        }else if(value>0 && value<=40){
             strength = Strength.LOW;
        }else if(value>40 && value<=60){
            strength = Strength.MEDIUM;
        }else if(value>60 && value<=85){
            strength = Strength.HIGH;
        }else{
            strength = Strength.STRONG;
        }
        defenceObservableInterface.sendStrengthToUnits(strength);
    }//GEN-LAST:event_strengthSliderStateChanged

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currentTrackUnit;
    private javax.swing.JLabel currentTrackUnitLable;
    private javax.swing.JCheckBox isAreaCleared;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea msgToSend;
    private javax.swing.JPanel positionPanel;
    private javax.swing.JPanel recMsgPanel;
    private javax.swing.JLabel recMsgTitle;
    private javax.swing.JTextArea recievedMessages;
    private javax.swing.JRadioButton sendAllSelection;
    private javax.swing.JButton sendButton;
    private javax.swing.ButtonGroup sendMessageGroup;
    private javax.swing.JRadioButton sendUnitSelection;
    private javax.swing.JComboBox<String> sendUnitSelectionBox;
    private javax.swing.JSlider strengthSlider;
    private javax.swing.JComboBox<String> unitStatusComboBox;
    private javax.swing.JTextArea unitStatusTextArea;
    // End of variables declaration//GEN-END:variables
}
