/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.defence.maincontroller;
import com.defence.utilities.DefenceObservableInterface;
/**
 *
 * @author shami
 */
public class MainController extends javax.swing.JFrame  {
    private final DefenceObservableInterface defenceObservableInterface;
    private int msgSendSelection;
    /**
     * Creates new form MainController
     * @param defenceObservableInterface
     */
    public MainController(DefenceObservableInterface defenceObservableInterface) {
        initComponents();
        setVisible(true);
        this.defenceObservableInterface = defenceObservableInterface;
        
    }
    public void getMsg(String msg){
         recievedMessages.append("\n" + msg);
    }
    
    public void addUnitsToComboList(javax.swing.JComboBox<String> comboBox){
        comboBox.removeAllItems();
        String[] allUnits = defenceObservableInterface.getAllUnits();
        for (String unit : allUnits) {
            comboBox.addItem(unit);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sendMessageGroup = new javax.swing.ButtonGroup();
        isAreaCleared = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        msgToSend = new javax.swing.JTextArea();
        sendButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        recievedMessages = new javax.swing.JTextArea();
        sendAllSelection = new javax.swing.JRadioButton();
        sendUnitSelection = new javax.swing.JRadioButton();
        sendUnitSelectionBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Controller");

        isAreaCleared.setText("Area Cleared");
        isAreaCleared.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isAreaClearedActionPerformed(evt);
            }
        });

        msgToSend.setColumns(20);
        msgToSend.setLineWrap(true);
        msgToSend.setRows(5);
        jScrollPane1.setViewportView(msgToSend);

        sendButton.setText("send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        recievedMessages.setEditable(false);
        recievedMessages.setColumns(20);
        recievedMessages.setLineWrap(true);
        recievedMessages.setRows(5);
        jScrollPane2.setViewportView(recievedMessages);

        sendMessageGroup.add(sendAllSelection);
        sendAllSelection.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        sendAllSelection.setText("to All Units");
        sendAllSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendAllSelectionActionPerformed(evt);
            }
        });

        sendMessageGroup.add(sendUnitSelection);
        sendUnitSelection.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        sendUnitSelection.setText("to a Selectecd Unit");
        sendUnitSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendUnitSelectionActionPerformed(evt);
            }
        });

        sendUnitSelectionBox.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        sendUnitSelectionBox.setEnabled(false);
        sendUnitSelectionBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendUnitSelectionBoxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sendUnitSelectionBoxMouseEntered(evt);
            }
        });
        sendUnitSelectionBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendUnitSelectionBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(isAreaCleared, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 250, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sendAllSelection)
                                    .addComponent(sendUnitSelectionBox, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sendUnitSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sendButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(sendAllSelection)
                .addGap(18, 18, 18)
                .addComponent(sendUnitSelection)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sendUnitSelectionBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sendButton)
                .addGap(0, 10, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(isAreaCleared)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void isAreaClearedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isAreaClearedActionPerformed
        // TODO add your handling code here:
        if(isAreaCleared.isSelected()){
            defenceObservableInterface.sendAreaStatus(1);
        }else{
            defenceObservableInterface.sendAreaStatus(0);
        }
    }//GEN-LAST:event_isAreaClearedActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        // TODO add your handling code here:
        if(msgSendSelection ==1){
             if(!msgToSend.getText().equals("")){
             defenceObservableInterface.sendMsgtoAllUnits("Eagle : "+msgToSend.getText() +"\n");
             msgToSend.setText("");  
        }     
        }
        if(msgSendSelection ==2){
             if(!msgToSend.getText().equals("")){
              int indexOfSelection = sendUnitSelectionBox.getSelectedIndex();
              defenceObservableInterface.sendMsgtoUnitInIndex(indexOfSelection,("Eagle : "+msgToSend.getText() +"\n"));
              msgToSend.setText("");     
        }
        
        }
       
    }//GEN-LAST:event_sendButtonActionPerformed

    private void sendAllSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendAllSelectionActionPerformed
        // TODO add your handling code here:
        msgSendSelection = 1;
        sendUnitSelectionBox.setEnabled(false);
    }//GEN-LAST:event_sendAllSelectionActionPerformed

    private void sendUnitSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendUnitSelectionActionPerformed
        // TODO add your handling code here:
        msgSendSelection = 2;
        addUnitsToComboList(sendUnitSelectionBox);
        sendUnitSelectionBox.setEnabled(true);
    }//GEN-LAST:event_sendUnitSelectionActionPerformed

    private void sendUnitSelectionBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendUnitSelectionBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendUnitSelectionBoxActionPerformed

    private void sendUnitSelectionBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendUnitSelectionBoxMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_sendUnitSelectionBoxMouseEntered

    private void sendUnitSelectionBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sendUnitSelectionBoxMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sendUnitSelectionBoxMouseClicked

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox isAreaCleared;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea msgToSend;
    private javax.swing.JTextArea recievedMessages;
    private javax.swing.JRadioButton sendAllSelection;
    private javax.swing.JButton sendButton;
    private javax.swing.ButtonGroup sendMessageGroup;
    private javax.swing.JRadioButton sendUnitSelection;
    private javax.swing.JComboBox<String> sendUnitSelectionBox;
    // End of variables declaration//GEN-END:variables
}
